### ISSUE TITLE
Different behaviour between Trackbanks

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#51] opened 2015-04-26 16:29 UTC
Hey,

lets say we have 17 Instrument tracks and 17 Effect tracks.
We toggle the audio/instrument trackbank and move to the first track in the trackbank.

so:
/track/bank/page/- (to reach the first 8 tracks)
/track/- (to move to the first track in the bank)

this doesn't work with the effect tracks
In the effect bank we cannot reach the first 8 tracks basically, it always jumps to track 9 when we hit 
/track/bank/page/- 

Here is the updated Lemur template i use with the toggle: http://filehorst.de/d/bvhqxGdg

**Comment by git-moss** [comment] 2015-04-28 08:47
I can reproduce it. Seems to be a Bitwig bug at first sight but will need to do some further testing.

**Comment by git-moss** [comment] 2015-04-28 19:25
Got it! That was a tough one but it is fixed now :-)

**Closed by git-moss** 2015-04-28 19:25 UTC

**Comment by Lucid-Network** [comment] 2015-04-29 11:36
Cool :)
